### ISSUE TITLE
Only the placeholders are shown

### ISSUE THREAD

**Issue by dan-nkl** [Brad126735/JobBoard#1]
/jobs

![image](https://user-images.githubusercontent.com/26377301/29245824-558d8a70-7fe6-11e7-9858-99d8302922b4.png)

JobBoard 1.0
Server is running CraftBukkit version git-Spigot-65e8124-963b19c (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

Plugin list: https://paste.nikul.in/?3d09e5e64117d333#Ufa74VzdU3ZDUBUPZoKGaoOBOlC7zDCKV8V0Zy5trW0=

**Comment by Brad126735** [comment]
My mistake, looks like a parenthesis was in the wrong place. Will be fixed with 1.1.
